name: CI

on:
  push:
    branches: [ main, rust ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  infrastructure:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v4
      # - uses: azure/arm-deploy@v2
      #   with:
      #     scope: resourcegroup
      #     resourceGroupName: rg-website-test-001
      #     template: main.bicep

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: mcpuacr.azurecr.io

      - uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server" # ??
          tags: mcpuacr.azurecr.io/rust-std-web-server:latest
          push: true
